### ISSUE TITLE
Error in stri_detect_regex when calling kwic 

### ISSUE THREAD

**Issue by syd-doyen** [quanteda/quanteda#1579] opened 2019-01-28 05:19 UTC
## Describe the bug

Hi. Quanteda is a great package that we have enjoyed using. 

When calling  kwic from  Quanteda v 1.3.14 I get the following error:

Error in stri_detect_regex(types_search, utils::glob2rx(pattern), case_insensitive = FALSE) : 
  Incorrectly nested parentheses in regexp pattern. (U_REGEX_MISMATCHED_PAREN)

In the example below the first call to kwic raises the error while the second
does not find the phrase. Not sure why. 

Perhaps this has been discussed before but I could not find a definite
answer that worked.

## Reproducible code

```r
library(quanteda)

# this returns the error above
quanteda::kwic("sharp pleuritic l) axilla pain",quanteda::phrase("*l) axilla pain*"),window=6,valuetype="glob")

# lets use glob2rx  - same error
p= glob2rx("*l) axilla pain*")
quanteda::kwic("sharp pleuritic l) axilla pain",quanteda::phrase(p),window=6,valuetype="regex")

# a possible work around by escaping the ")"
# return kwic object with 0 rows not sure why
p= glob2rx("*l\\) axilla pain*")
quanteda::kwic("sharp pleuritic l) axilla pain",quanteda::phrase(p),window=6,valuetype="regex")

```

## Expected behavior

I did not think one would have to escape special characters when calling kwic and "glob".
If I have tried using glob2rx but obviously I do not how to do it correctly
or there is a bug somewhere. 

I expected that both calls to kwic would provide the same result. 

## System information

Please run `sessionInfo()` and paste the output.
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2   stringr_1.3.1    portrpaths_0.3.1 dplyr_0.7.8      readr_1.3.1     
[6] extrafont_0.17  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         quanteda_1.3.14    plyr_1.8.4         pillar_1.3.1      
 [5] compiler_3.5.2     RColorBrewer_1.1-2 bindr_0.1.1        stopwords_0.9.0   
 [9] tools_3.5.2        lubridate_1.7.4    jsonlite_1.6       tibble_2.0.0      
[13] gtable_0.2.0       lattice_0.20-38    pkgconfig_2.0.2    rlang_0.3.0.1     
[17] fastmatch_1.1-0    Matrix_1.2-15      rstudioapi_0.8     CLACK_1.0.1       
[21] yaml_2.2.0         Rttf2pt1_1.3.7     hms_0.4.2          wordcloud_2.6     
[25] grid_3.5.2         tidyselect_0.2.5   glue_1.3.0         data.table_1.12.0 
[29] R6_2.3.0           spacyr_1.0         purrr_0.2.5        ggplot2_3.1.0     
[33] extrafontdb_1.0    magrittr_1.5       scales_1.0.0       rlist_0.4.6.1     
[37] assertthat_0.2.0   colorspace_1.3-2   logging_0.8-104    stringi_1.2.4     
[41] RcppParallel_4.4.2 lazyeval_0.2.1     munsell_0.5.0      crayon_1.3.4      
> 
```

**Comment by koheiw** [comment] 2019-01-30 09:09
It seems that `glob2rx` does not escape closing parentheses, and it is the cause of the error.
```r
> utils::glob2rx("*abc d)")
[1] "^.*abc d)$"
> utils::glob2rx("*abc (d")
[1] "^.*abc \\(d$"
> utils::glob2rx("*abc (d)")
[1] "^.*abc \\(d)$"
```
I am not sure if this is a bug as it is from a well established package. Meanwhile, my suggesting is to use `valuetype = regex` manual escaping special characters.

`"*l\\) axilla pain*"` should work but tokenization must be `what = "fastestword"`.
```r
> tokens("sharp pleuritic l) axilla pain")
tokens from 1 document.
text1 :
[1] "sharp"     "pleuritic" "l"         ")"         "axilla"    "pain"     

> tokens("sharp pleuritic l) axilla pain", what = "fastestword")
tokens from 1 document.
text1 :
[1] "sharp"     "pleuritic" "l)"        "axilla"    "pain"     
```

**Comment by kbenoit** [comment] 2019-02-03 04:57
From `?glob2rx`:

> Note that now even (, [ and { can be used in `pattern`, but `glob2rx()` may not work correctly with arbitrary characters in `pattern`.

Not really clear what that means, but it suggests that parentheses should be usable, as regular pattern characters and not regular expression characters, in the glob `pattern`.

**Comment by kbenoit** [comment] 2019-05-13 07:50
It's not really a bug, but rather a "feature" of the particular flavour of regular expressions that R uses by default.  Most closing braces and brackets do not need escaping, although generally, closing parentheses ("round brackets") do.  

So, the results of `glob2rx()` fail with `perl = TRUE` and fails in **stringi**'s regex usage.

``` r
patt <- glob2rx("(?)*")
txt <- c("(1)a", "(2)anything", "2)b", "(xx")

grepl(patt, txt)
## [1]  TRUE  TRUE FALSE FALSE
grepl(patt, txt, perl = TRUE)
## Warning in grepl(patt, txt, perl = TRUE): PCRE pattern compilation error
##  'unmatched parentheses'
##  at ')'
## Error in grepl(patt, txt, perl = TRUE): invalid regular expression '^\(.)'
stri_detect_regex(txt, patt)
## Error in stri_detect_regex(txt, patt): could not find function "stri_detect_regex"
```

**Solution?** We adapt the `glob2rx()` function to escape closing parentheses.

**Comment by mstr3336** [comment] 2020-04-30 07:49
Hi all - 
I'm wondering what the status on this issue is - Are there plans to resolve this?

**Comment by kbenoit** [comment] 2020-04-30 08:16
I think your best bet is a workaround that does not run into the closing parenthesis problem. Here are several possibilities:

``` r
library("quanteda")
## Package version: 2.0.1
sessionInfo()$R.version$version.string
## [1] "R version 4.0.0 (2020-04-24)"

toks_fw <- tokens("sharp pleuritic l) axilla pain", what = "fasterword")
toks_fw
## Tokens consisting of 1 document.
## text1 :
## [1] "sharp"     "pleuritic" "l)"        "axilla"    "pain"
# fails
kwic(toks_fw, pattern = phrase("*l) axilla pain*"), valuetype = "glob")
## Error in stri_detect_regex(types_search, utils::glob2rx(pattern), case_insensitive = FALSE): Incorrectly nested parentheses in regexp pattern. (U_REGEX_MISMATCHED_PAREN)
# works
kwic(toks_fw, pattern = phrase("*l\\) axilla pain*"), valuetype = "glob")
##                                                  
##  [text1, 3:5] sharp pleuritic | l) axilla pain |
# works, equivalent
kwic(toks_fw, pattern = phrase(".*l\\)$ ^axilla$ ^pain.*"), valuetype = "regex")
##                                                  
##  [text1, 3:5] sharp pleuritic | l) axilla pain |

# this also works - here the ) is separated
toks_w <- tokens("sharp pleuritic l) axilla pain", what = "word")
toks_w
## Tokens consisting of 1 document.
## text1 :
## [1] "sharp"     "pleuritic" "l"         ")"         "axilla"    "pain"
kwic(toks_w, pattern = phrase("*l ) axilla pain*"), valuetype = "glob")
##                                                   
##  [text1, 3:6] sharp pleuritic | l ) axilla pain |
```

**Closed** 2023-05-11 13:46 UTC
