### ISSUE TITLE
textplot_network labelsize

### ISSUE THREAD

**Issue by dmuijen** [quanteda/quanteda#1681] opened 2019-05-06 13:48 UTC
## Describe the bug

Hello, the vertex_labelsize argument doesn't respond to changes. 

## Reproducible code

```r
toks <- corpus_subset(data_corpus_irishbudget2010) %>%
  tokens(remove_punct = TRUE) %>%
  tokens_tolower() %>%
  tokens_remove(pattern = stopwords("english"), padding = FALSE)
fcmat <- fcm(toks, context = "window", tri = FALSE)
feat <- names(topfeatures(fcmat, 30))
fcm_select(fcmat, pattern = feat) %>%
  textplot_network(min_freq = 0.5, vertex_labelsize = 50)
```

## Expected behavior

Expected labels to change in size but it doesn't. Shouldn't size go outside of the aes similar to labelcolor?

```r
            ggrepel::geom_text_repel(data = vertex,
                                     aes(x, y, label = label, size = vertex$labelsize),
                                     segment.color = vertex$color,
                                     segment.size = 0.2,
                                     color = vertex$labelcolor,
family = font)
```

## System information

Please run `sessionInfo()` and paste the output.
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /opt/R/3.5.2/lib/R/lib/libRblas.so
LAPACK: /opt/R/3.5.2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shinyWidgets_0.4.8 shiny_1.3.2        ggraph_1.0.2       igraph_1.2.4       ggrepel_0.8.0      tidyr_0.8.3        ggthemes_4.1.0     ggplot2_3.1.0     
 [9] tm_0.7-6           NLP_0.2-0          dplyr_0.8.0.1      readtext_0.71      quanteda_1.4.3     spacyr_1.0        

loaded via a namespace (and not attached):
 [1] viridis_0.5.1        httr_1.4.0           jsonlite_1.6         viridisLite_0.3.0    network_1.15         RcppParallel_4.4.2   assertthat_0.2.1    
 [8] pdftools_2.2         askpass_1.1          yaml_2.2.0           slam_0.1-45          qpdf_1.1             pillar_1.3.1         lattice_0.20-38     
[15] glue_1.3.1           reticulate_1.11.1    digest_0.6.18        promises_1.0.1       polyclip_1.10-0      colorspace_1.4-1     htmltools_0.3.6     
[22] httpuv_1.5.1         Matrix_1.2-15        plyr_1.8.4           pkgconfig_2.0.2      purrr_0.3.2          xtable_1.8-4         scales_1.0.0        
[29] tweenr_1.0.1         sna_2.4              later_0.8.0          ggforce_0.2.2        tibble_2.1.1         farver_1.1.0         withr_2.1.2         
[36] lazyeval_0.2.2       cli_1.1.0            magrittr_1.5         crayon_1.3.4         statnet.common_4.2.0 mime_0.6             evaluate_0.13       
[43] stopwords_0.9.0      fansi_0.4.0          MASS_7.3-51.1        xml2_1.2.0           tools_3.5.2          data.table_1.12.0    stringr_1.4.0       
[50] munsell_0.5.0        compiler_3.5.2       rlang_0.3.4          grid_3.5.2           rstudioapi_0.10      labeling_0.3         rmarkdown_1.12      
[57] gtable_0.3.0         R6_2.4.0             gridExtra_2.3        lubridate_1.7.4      knitr_1.22           utf8_1.1.4           fastmatch_1.1-0     
[64] stringi_1.4.3        parallel_3.5.2       Rcpp_1.0.1           xfun_0.5             tidyselect_0.2.5     coda_0.19-2         
```

## Additional info

Please add any other information about the issue.

**Comment by jiongweilua** [comment] 2019-05-06 14:39
Hi @dmuijen 

Thanks for pointing this out! Supplying `size=vertex$labelsize` outside of the `aes(...)` fixes the problem as you suggested.

I introduced  `vertex_labelsize`  in a quick fix for #1564  to allow different text label sizes (such as according to relative frequencies).  In my haste, I only tested it when different frequency vectors were supplied, but I failed to test how it will behave if supplied with different integer values. 

Can I check with you if the following behaviour solves the problem? If so, I will raise a pull request and close this issue.

```r
library(dplyr)
library(quanteda)
toks <- corpus_subset(data_corpus_irishbudget2010) %>%
    tokens(remove_punct = TRUE) %>%
    tokens_tolower() %>%
    tokens_remove(pattern = stopwords("english"), padding = FALSE)
fcmat <- fcm(toks, context = "window", tri = FALSE)
feat <- names(topfeatures(fcmat, 30))

fcm_30 <- fcm_select(fcmat, pattern = feat)

textplot_network(fcm_30,
                 vertex_labelsize = 5)
```
![image](https://user-images.githubusercontent.com/28591528/57232378-5dfc8d80-7014-11e9-891f-2bbd2e10fda4.png)

```r
textplot_network(fcm_30,
                 vertex_labelsize = 10)
```
![image](https://user-images.githubusercontent.com/28591528/57232386-6228ab00-7014-11e9-8676-5d3c9d05e447.png)

```r
Label size scaled according to relative frequencies
textplot_network(fcm_30,
                 vertex_labelsize = rowSums(fcm_30)/min(rowSums(fcm_30)))
```
![image](https://user-images.githubusercontent.com/28591528/57232393-65bc3200-7014-11e9-89c1-f1a10a39dbda.png)

**Comment by dmuijen** [comment] 2019-05-06 15:37
Thanks for the prompt response ! And overall great work on the package, been able to do so much with all the functionality including connection to spaCy. 

Behaviour sketched above solved the issue indeed, I will opt for the frequency vector variant in the meantime -- overlooked that option, thanks!

**Closed** 2019-05-14 08:49 UTC

**Comment by contefranz** [comment] 2019-07-09 10:42
@jiongweilua I am sorry but it seems I am not able to control `vertex_labelsize` as I would like to. Here is an example: 

```r
library(dplyr)
library(quanteda)
toks <- corpus_subset(data_corpus_irishbudget2010) %>%
    tokens(remove_punct = TRUE) %>%
    tokens_tolower() %>%
    tokens_remove(pattern = stopwords("english"), padding = FALSE)
fcmat <- fcm(toks, context = "window", tri = FALSE)
feat <- names(topfeatures(fcmat, 30))

fcm_30 <- fcm_select(fcmat, pattern = feat)

textplot_network(fcm_30, vertex_labelsize = 5)
```
![plot_zoom_png](https://user-images.githubusercontent.com/10447584/60881694-812aff80-a246-11e9-99b3-f6487495024f.png)

Now I increase the size: 

```r
textplot_network(fcm_30, vertex_labelsize = 20)
```
![plot_zoom_png2](https://user-images.githubusercontent.com/10447584/60881774-b8011580-a246-11e9-9ef1-b25352081b79.png)

And as you can see, I have no effect. 

Here my `sessionInfo()` output


```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.1       lemon_0.4.3       gridExtra_2.3     ggplot2_3.1.1     quanteda_1.5.0    stringr_1.4.0    
[7] data.table_1.12.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1           sna_2.4              RColorBrewer_1.1-2   pillar_1.4.1         compiler_3.5.2      
 [6] plyr_1.8.4           tools_3.5.2          stopwords_0.9.0      lubridate_1.7.4      tibble_2.1.2        
[11] gtable_0.3.0         lattice_0.20-38      pkgconfig_2.0.2      rlang_0.3.4          Matrix_1.2-17       
[16] fastmatch_1.1-0      rstudioapi_0.10      ggrepel_0.8.1        xfun_0.7             coda_0.19-2         
[21] knitr_1.23           withr_2.1.2          tidyselect_0.2.5     glue_1.3.1           R6_2.4.0            
[26] purrr_0.3.2          spacyr_1.0           magrittr_1.5         ISOcodes_2019.04.22  scales_1.0.0        
[31] assertthat_0.2.1     xtable_1.8-4         colorspace_1.4-1     labeling_0.3         stringi_1.4.3       
[36] network_1.15         lazyeval_0.2.2       RcppParallel_4.4.3   munsell_0.5.0        statnet.common_4.3.0
[41] crayon_1.3.4        
```

What am I missing? 
Could you please provide a tutorial on how to achieve the goal?

**Comment by amatsuo** [comment] 2019-07-09 10:49
The option works in my environment. So, I'm not sure what's the issue... How did you save the pictures?

```R
textplot_network(fcm_30, vertex_labelsize = 5)
ggplot2::ggsave("~/Desktop/temp/label_size_5.png", width = 5, height = 5)

textplot_network(fcm_30, vertex_labelsize = 20)
ggplot2::ggsave("~/Desktop/temp/label_size_20.png", width = 5, height = 5)
```

![image](https://user-images.githubusercontent.com/8436792/60882211-4d98a700-a23f-11e9-8ebd-3eb117355b0e.png)

![image](https://user-images.githubusercontent.com/8436792/60882244-5c7f5980-a23f-11e9-806b-4f9f491f3474.png)

**Comment by contefranz** [comment] 2019-07-09 10:55
@amatsuo Actually the plots are not even rendered correctly in RStudio. So it doesn't matter how I save the plots. Could you please post your `sessionInfo()`?

**Comment by gabrielparriaux** [comment] 2022-08-03 12:59
Hello,

I’m using this code to plot a network with label sizes proportionals to the number of co-occurrences of tokens.

```r
textplot_network(my_fcm, vertex_labelsize = 0.034* rowSums(my_fcm)/min(rowSums(my_fcm)))
```

I have to multiply by a small number, otherwise labels are gigantic and hide everything. 

It’s quite ok, but the problem is that some words appear to be really too big and other really too small. I would like the increase in size to be more progressive (minimum and maximum size less extreme). I tried some adjustments, but without success… Is there an easy way to plot the labelsize more progressively?

I add the image produced to give you an idea.

Thanks a lot for your help,

Gabriel

![textplot_network](https://user-images.githubusercontent.com/125275/182613500-27749fd2-788f-4cf3-8fee-04ac58cc3ae5.png)
