### ISSUE TITLE
“dgTMatrix” error while building dfm from a certain unigrams combination

### ISSUE THREAD

**Issue by marshwiggle** [quanteda/quanteda#1747] opened 2019-09-23 19:54 UTC
## Bug Description

I'm trying to build a dfm from this "corpus" of tokens: [unigrams.txt](https://github.com/quanteda/quanteda/files/3643804/unigrams.txt)

Get the following error:
```r
Error in  validObject(r) :
  invalid class “dgTMatrix” object: all column indices (slot 'j') must be between 0 and ncol-1 in a TsparseMatrix
```

## Reproducible code

```r
> unigrams <- dget("unigrams.txt")
> class(unigrams)
[1] "tokens"
> dfm(unigrams)
Error in validObject(r) :
  invalid class “dgTMatrix” object: all column indices (slot 'j') must be between 0 and ncol-1 in a TsparseMatrix
```
I've got the same error with `dfm(unigrams[5:7])`, `dfm(unigrams[4:7])`, `dfm(unigrams[3:7])`, `dfm(unigrams[2:7])`, while, for example, `dfm(unigrams[1:6])` or `dfm(unigrams[6:7])` work as expected. 

## System Information

My system information:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.3

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=ru_RU.UTF-8    
 [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_1.5.1 readr_1.3.1   
```

**Comment by kbenoit** [comment] 2019-09-23 20:14
In a `tokens` class object, the "" is not an actual token but reserved for a special "null" token. Your serialization of the object in dput apparently has reassigned that slot. It works fine if you recreate the object after making it a simple list:

``` r
library("quanteda")
## Package version: 1.5.1
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View

unigrams <- dget("~/Downloads/unigrams.txt")
dfmat <- dfm(as.tokens(as.list(unigrams)))

dfmat
## Document-feature matrix of: 7 documents, 156 features (82.7% sparse).

featnames(dfmat)
##   [1] "heat"        "the"         "oil"         "for"         "sauce"      
##   [6] "in"          "a"           "small"       "pan"         "add"        
##  [11] "garlic"      "ginger"      "jalapeños"   "or"          "serranos"   
##  [16] "and"         "green"       "onions"      "cook"        "about"      
##  [21] "minutes"     "whisk"       "remaining"   "ingredients" "through"    
##  [26] "turn"        "off"         "seth's"      "new"         "book"       
##  [31] "it"          "was"         "really"      "cool"        "to"         
##  [36] "see"         "so"          "many"        "of"          "my"         
##  [41] "into"        "your"        "room"        "after"       "night"      
##  [46] "rain"        "against"     "all"         "advice"      "that"       
##  [51] "rest"        "family"      "would"       "deal"        "with"       
##  [56] "mr"          "mrs"         "youngest"    "cancel"      "their"      
##  [61] "flights"     "retrieve"    "baggage"     "deeply"      "upset"      
##  [66] "they"        "arrange"     "vet"         "investigate" "dog"        
##  [71] "check"       "pet"         "insurance"   "end"         "has"        
##  [76] "have"        "an"          "operation"   "remove"      "blood"      
##  [81] "clot"        "from"        "its"         "spine"       "counting"   
##  [86] "we"          "still"       "don't"       "know"        "whether"    
##  [91] "he's"        "going"       "pull"        "here's"      "hoping"     
##  [96] "this"        "is"          "measure"     "society's"   "willingness"
## [101] "take"        "risks"       "culture"     "high"        "uncertainty"
## [106] "avoidance"   "people"      "are"         "more"        "likely"     
## [111] "hold"        "out"         "sure"        "bet"         "not"        
## [116] "try"         "fix"         "what"        "isn't"       "broken"     
## [121] "low"         "you're"      "risk"        "takers"      "innovators" 
## [126] "who"         "mind"        "bit"         "life"        "do"         
## [131] "i"           "regret"      "oh"          "yeah"        "months"     
## [136] "walked"      "by"          "storefront"  "on"          "atlantic"   
## [141] "avenue"      "whose"       "windows"     "were"        "covered"    
## [146] "image"       "cartoon"     "character"   "always"      "assumed"    
## [151] "be"          "graphic"     "design"      "office"      "comicbook"  
## [156] "store"
```

**Comment by marshwiggle** [comment] 2019-09-23 20:22
Thank you very much!

But why do `unigrams[6:7]` work without any error?

**Comment by kbenoit** [comment] 2019-09-24 09:45
I'm pretty sure that the breaking cases fail because the include the pair of `unigrams[5]` and `unigrams[7]`. The `""` is assigned a regular index in `unigrams[7]`, which is not how the `tokens()` constructor would treat this special element. The token `"life"` is the last indexed token in `unigrams` (index 160) but this index position is dropped when the tokens object is reprocessed, for instance by `dfm()`, which means that there is no corresponding index for 160.

Serializing a `tokens` object works fine in my tests:

``` r
library("quanteda")
#> Package version: 1.5.2
#> Parallel computing: 2 of 8 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
tokens("a b c") %>%
    tokens_remove("b", pad = TRUE)
#> tokens from 1 document.
#> text1 :
#> [1] "a" ""  "c"

tokens("a b c") %>%
    tokens_remove("b", pad = TRUE) %>%
    dput()
#> structure(list(text1 = c(1L, 0L, 2L)), types = c("a", "c"), padding = TRUE, class = "tokens", what = "word", ngrams = 1L, skip = 0L, concatenator = "_", docvars = structure(list(), .Names = character(0), class = "data.frame", row.names = "text1"))
```

since the pad is correctly assigned the index of 0. The error seems to be coming from something that happened to your dputted object `unigrams.txt`. @koheiw might also have suggestions.

<sup>Created on 2019-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jogrue** [comment] 2019-11-15 15:07
I was just about to open a new issue when I stumbled upon this one. I had gotten the same error message when I tried to build a dfm from a corpus. I could tokenize the corpus, but then again, building the dfm failed. I also tried to build the dfm from the texts alone (as a simple character object), which also failed.

My corpus consists of Facebook posts and Tweets, each is a document. In total there are 376074 documents. Figuring out which text/document is the culprit is, therefore, rather difficult. At least for me, since I have no idea what to look for. At some point in the past, this has worked as intended, so maybe the error was introduced by some newly added Tweet/post or by a recent update in quanteda.

My data are tibbles containing posts/Tweets and metadata downloaded from Facebook/Twitter through their API and then combined into one big tibble (which is then transformed into a quanteda corpus). In the process I save and read the data with saveRDS/readRDS.

What fixed it for me was to transform the corpus to the sentence-level and then return it to the document level.

``` r
# Does not work
sm_dfm <- sm_corp %>%
  dfm()

# Works
sm_dfm <- sm_corp %>%
  corpus_reshape(to = "sentences") %>%
  corpus_reshape(to = "documents") %>%
  dfm()
```

Any ideas on what I could look for? This might as well be a separate issue from the one above?

Also, I am on Windows 10 x64, quanteda 1.5.1, and R version 3.6.1.

**Comment by kbenoit** [comment] 2019-11-15 17:15
@jogrue This sounds like the same issue, but is potentially different since you are starting from a corpus rather than the raw input text. I'd be happy to diagnose the exact issue if you can pinpoint and (privately) send me a link to the corpus itself.

One quick way to narrow it down is to split the corpus in halves, to see which cause the problem, and then keep halving them to get the size down. e.g.

```r
sm_corp[1 : floor(ndoc(sm_corp)/2)] %>%
    dfm()
sm_corp[ceiling(ndoc(sm_corp)/2) : ndoc(sm_corp)] %>%
    dfm()
```

**Comment by onesandzeroes** [comment] 2019-12-18 23:49
I've just run into this error on a large corpus of reviews scraped from the internet. Following your suggestion to split the corpus in half to narrow down the error, I was able to trace it to a single document that contains a unicode character \#65279, a "zero width no-break space", which gets converted to an empty token. 

The offending document is row 6 in [the dataset I've uploaded here](https://www.dropbox.com/s/rnr9p2eloq5okdj/bad_corpus.rds?dl=0) (I reduced it to just 8 rows). Attempting to create a `dfm` from the `comments` column produces the error:

```r
library(quanteda)

bad <- readRDS("bad_corpus.rds")
dfm(bad$comments)
# Error in validObject(r) : 
#  invalid class “dgTMatrix” object: all column indices (slot 'j') must be between 0 and ncol-1 in a TsparseMatrix

# Check unicode for document that causes errors:
utf8ToInt(bad$comments[6])
```

I am on macOS 10.14.6, quanteda 1.5.2, R 3.6.1.

**Comment by koheiw** [comment] 2019-12-19 08:06
Hi @onesandzeroes thanks for the report. I recently noticed this problem and addressed in the Github version. Why don't you try?

```r
> dfm(tokens(bad_corpus$comments))
Document-feature matrix of: 8 documents, 349 features (77.6% sparse).
```

**Comment by onesandzeroes** [comment] 2019-12-19 22:24
Thanks @koheiw , I've just installed the Github version and it looks like this has been fixed.

Using v1.5.2, both ways of creating the corpus producing the error:

```r
> dfm(bad$comments)
Error in validObject(r) : 
  invalid class “dgTMatrix” object: all column indices (slot 'j') must be between 0 and ncol-1 in a TsparseMatrix
> dfm(tokens(bad$comments))
Error in validObject(r) : 
  invalid class “dgTMatrix” object: all column indices (slot 'j') must be between 0 and ncol-1 in a TsparseMatrix
```

Installing the latest from master with `devtools::install_github("quanteda/quanteda")`, both methods work:

```r
> dfm(bad$comments)
Document-feature matrix of: 8 documents, 349 features (77.6% sparse).
> dfm(tokens(bad$comments))
Document-feature matrix of: 8 documents, 349 features (77.6% sparse).
```

**Comment by koheiw** [comment] 2019-12-20 06:43
Thanks. Good to see it working for you.

**Closed by koheiw** 2019-12-20 06:43 UTC

**Comment by jogrue** [comment] 2020-01-03 12:28
I just wanted to get back to this issue now—sorry, I did not manage to have a closer look earlier. Great to see it fixed already and thanks a lot to @onesandzeroes and @koheiw!
